### ISSUE TITLE
Adding base conversions

### ISSUE THREAD

**Issue by DamienLegay** [tommens/calculator-cucumber#23]
It would be nice to be able to convert numbers between different bases. For instance, 255 in base 10 (decimal) is equal to 11111111 in base 2 (binary) and FF in base 16 (hexadecimal). Ideally, the calculator would be able to handle any base > 1.

This can be extended to rational and even real numbers.

**Comment by tommens** [comment]
This issue request is overlapping with #11 which is about supporting different number formats and different number representations. I agree it would be nice, but it should be part of that issue request.

**Comment by DamienLegay** [comment]
My bad, hadn't noticed.
